{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: tmplsvc-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tmplsvc.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_password: {{ .Values.secret.password | quote }}
{{- end }}
{{- if and .Values.auth.keys.kid .Values.auth.keys.pem }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.keys.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tmplsvc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.keys.kid }}.pem: {{ .Values.auth.keys.pem | b64enc }}
{{- end }}
